# Generated by Django 3.2.7 on 2021-09-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repo_link',
        ),
    ]
