# Generated by Django 3.2.7 on 2021-09-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_auto_20210927_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='note_project',
            new_name='name',
        ),
    ]
