# Generated by Django 3.2.7 on 2021-09-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_rename_note_project_todo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.URLField(default=None, max_length=100),
        ),
    ]
