# Generated by Django 3.2.7 on 2021-09-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0007_auto_20210927_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Todo.project'),
        ),
    ]
